# Generated by Django 6.0.4 on 2026-04-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Front', 'Back', 'Side'", max_length=100)),
                ('base_image', models.ImageField(upload_to='products/base_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_left_x', models.IntegerField(help_text='X coordinate of the top-left corner')),
                ('top_left_y', models.IntegerField(help_text='Y coordinate of the top-left corner')),
                ('top_right_x', models.IntegerField()),
                ('top_right_y', models.IntegerField()),
                ('bottom_right_x', models.IntegerField()),
                ('bottom_right_y', models.IntegerField()),
                ('bottom_left_x', models.IntegerField()),
                ('bottom_left_y', models.IntegerField()),
                ('product_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_area', to='products.productview')),
            ],
        ),
    ]
